image_index:
    path:     /
    defaults: { _controller: "MainBundle:Image:index" }
    methods:  GET

image_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Image:show" }
    methods:  GET

image_new:
    path:     /new
    defaults: { _controller: "MainBundle:Image:new" }
    methods:  [GET, POST]

image_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Image:edit" }
    methods:  [GET, POST]

image_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Image:delete" }
    methods:  DELETE
